blob_detection: main.cpp
	@echo "Building.."
	@g++ main.cpp src/blob_detection.cpp -o blob -lopencv_core -lopencv_imgcodecs -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lsqlite3 -lgdal


clean:
	rm blob_detection